### ISSUE TITLE
README outdated

### ISSUE THREAD

**Issue by knector01** [knector01/inv.lua#15]
GitGet seems to be confused by this repository, so point people to a different method such as clone.lua.

Client/server scripts were renamed as well

**Comment by faroob** [comment]
i am also having this issue

**Comment by lewark** [comment]
@faroob 

What issue in particular did you run into? Were there issues downloading the program in game, or was it a documentation-related problem?

**Comment by faroob** [comment]
Sorry, it was a problem with gitget, i managed to download and install with a diffrent github grabber.
